default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: hanblog_production
  username: deployer
  password: <%= ENV["HAVLOVE_DATABASE_PASSWORD"] %>
  host: localhost